services:
  api:
    build: .
    container_name: analyse-fpl-be
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - ENV=production
      - PYTHONUNBUFFERED=1
    volumes:
      - /root/analyse-fpl/analyse-fpl-be/FPL-Core-Insights/data:/app/FPL-Core-Insights/data
